---
# tasks file for artifactory-role
- name: Ajout du repo Artifactory JFrog
  yum_repository:
    name: artifactory
    description: Repo officeil d'artifactory
    baseurl: https://releases.jfrog.io/artifactory/artifactory-rpms/
    gpgcheck: no
    gpgkey: https://releases.jfrog.io/artifactory/artifactory-rpms/repodata/repomd.xml.ey
    repo_gpgcheck: yes

- name : Installation Artifactory
  yum:
    name: jfrog-artifactory-oss

- name: Demarrage du service
  systemd:
    name: artifactory
    state: started
    enabled: yes
