---
# tasks file for artifactory-role
- name: Ajout du repo Artifactory JFrog
  yum_repository:
    name: artifactory
    description: Repo officil d'artifactory
    baseurl: https://releases.jfrog.io/artifactory/artifactory-rpms/
    gpgcheck: yes
    gpgkey: https://releases.jfrog.io/artifactory/artifactory-rpms/repodata/repomd.xml.key
    repo_gpgcheck: yes

- name : Installation Artifactory
  yum:
    name: jfrog-artifactory-oss

- name: Demarrage du service
  systemd:
    name: artifactory
    state: started
    enabled: yes
