---
- name: CI install
  hosts: jenkins
  become: yes
  roles:
  - role: maven-role
  - role: sonar-role
  tasks:
  - name: add repo Jenkins
    yum_repository:
      name: jenkins
      description: EPEL YUM repo
      baseurl: https://pkg.jenkins.io/redhat
      gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      gpgcheck: yes

  - name: install jenkins
    yum:
      update_cache: yes
      name:
        - java-11-openjdk-devel
        - jenkins
      state: present

  - name: start jenkins
    systemd:
      daemon_reload: yes
      name: jenkins
      state: started

  - name: enable jenkins
    systemd:
      name: jenkins
      enabled: true

  - name: sleep for 30 seconds and continue with play
    wait_for: timeout=30
    delegate_to: localhost

  - name: "Vérification si le fichier existe"
    stat:
      path: /var/lib/jenkins/secrets/initialAdminPassword
    register: _psswrd_file

  - name: init password jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkins_password
    when: _psswrd_file.stat.exists == true

  - name: print init password jenkins
    debug:
      var: jenkins_password.stdout

