---

- name: CI install
  hosts: jenkins
  become: yes
  tasks:
  - name: install wget
    yum:
      name: wget
      state: present

  - name: install openjdk
    yum:
      name: java-1.8.0-openjdk
      state: present

  - name: download jenkins.repo
    get_url:
      url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: import jenkins key
    rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: update
    yum: name=* state=latest

  - name: install jenkins
    yum:
      name: jenkins
      state: present

  - name: start jenkins
    systemd:
      name: jenkins
      state: started

  - name: enable jenkins
    systemd:
      name: jenkins
      enabled: true
