---
- name: install JAVA
  hosts: tomcat
  become: yes
  tasks:  
  - name: Install JAVA
    yum:
     name:
     - java-1.8.0-openjdk
    

- name: install tomcat
  hosts: tomcat
  become: yes
  roles:
  - tomcat-role


