---
# tasks file for docker-role
- name:
  yum:
    name:
    - yum-utils

- name: add repo config-manager
  yum_repository:
    name: docker
    description: local repo docker
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes

- name: install docker
  yum:
    update_cache: yes
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: launch docker
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: add user jenkins in docker group
  user:
    name: "{{docker_user}}"
    group: docker
    append: yes
  notify:
  - restart_jenkins
